### ISSUE TITLE
训练资源

### ISSUE THREAD

**Issue by jly0810** [Lxiangyue/GenN2N#1]
您好，我想问一下您的工作需要什么样的训练资源，训练时间大概为多久？
此外，代码什么时候公布？
您的工作非常令人赞叹！谢谢！

**Comment by Lxiangyue** [comment]
您好！ 感谢关注我们的工作！
我们使用的是单卡32GB的V100。训练时间和具体的NeRF场景大小，编辑任务有关，但大体在3-8h。我们目前也在对代码进行优化和加速，以期待发布的代码能达到更快的训练速度。
我们正在全力准备代码的开源，但具体时间还不太能确定哈，应该就在近期了，敬请期待！:)

**Comment by ThePassedWind** [comment]
您好，请问大概啥时候开源呀？

**Comment by Lxiangyue** [comment]
Released.
